DEFAULT: &DEFAULT
  black_list: [1, 2, 3]
  num_gpus_total: 4
  num_gpus_to_use: 1
  heads: 8
  dropout: 0.6
  edge_sampling_ratio: 0.9
  seed: 42
  verbose: 2
  save_model: False
  save_plot: False


GAT: &GAT
  model_name: GAT
  <<: *DEFAULT

GAT-Cora: &GAT-Cora
  <<: *GAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-Cora-NE:  &GAT-Cora-NE  # 0.8353
  <<: *GAT-Cora
  epochs: 500
  l2_lambda: 0.030641522044876367
  is_super_gat: False

GAT-Cora-NEO8: &GAT-Cora-NEO8  # 0.8387
  <<: *GAT-Cora-NE
  out_heads: 8
  l2_lambda: 0.011374239383259618

GAT-Cora-NEDP:  # 0.8379
  <<: *GAT-Cora-NE
  l2_lambda: 0.03772977329580155
  attention_type: "dot_product"

GAT-Cora-NEDPO8: &GAT-Cora-NEDPO8  # 0.8327
  <<: *GAT-Cora-NE
  out_heads: 8
  l2_lambda: 0.02512035167204263
  attention_type: "dot_product"

GAT-Cora-NEO8-ES: &GAT-Cora-NEO8-ES
  <<: *GAT-Cora-NEO8
  use_early_stop: True
  early_stop_patience: 255
  early_stop_queue_length: 426
  early_stop_threshold_loss: 0.038681044159681315
  early_stop_threshold_perf: 0.00020498344697281862
  epochs: 479

GAT-Cora-NEDPO8-ES: &GAT-Cora-NEDPO8-ES
  <<: *GAT-Cora-NEDPO8
  use_early_stop: True
  early_stop_patience: 460
  early_stop_queue_length: 140
  early_stop_threshold_loss: 4.7773561414675895e-05
  early_stop_threshold_perf: 0.0007206321329654777
  epochs: 489

GAT-Cora-EVL9O8:
  <<: *GAT-Cora-NE
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  use_pretraining: True
  total_pretraining_epoch: 1
  edge_sampling_ratio: 0.9483766465047745
  l2_lambda: 0.015463313539921298
  link_lambda: 2.2976901087679122
  neg_sample_ratio: 0.7

GAT-Cora-EVL12O8:  # 0.8426
  <<: *GAT-Cora-NE
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  edge_sampling_ratio: 0.9483766465047745
  l2_lambda: 0.015463313539921298
  link_lambda: 2.2976901087679122
  neg_sample_ratio: 0.6

GAT-Cora-EVL12O8-nsr01:  # 0.8442
  <<: *GAT-Cora-NE
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  edge_sampling_ratio: 0.6521925714114274
  l2_lambda: 0.015848820093969124
  link_lambda: 1.3893970517055363
  neg_sample_ratio: 0.1

GAT-Cora-E: &GAT-Cora-E
  <<: *GAT-Cora
  epochs: 500
  is_super_gat: True

GAT-Cora-EV1: &GAT-Cora-EV1
  <<: *GAT-Cora-E
  attention_type: "gat_originated"
  edge_sampling_ratio: 0.65491644887445
  l2_lambda: 0.011833069233159986
  att_lambda: 3.8805693322191623

GAT-Cora-EV1O8: &GAT-Cora-EV1O8  # 0.8388
  <<: *GAT-Cora-EV1
  out_heads: 8
  edge_sampling_ratio: 0.7134104373394458
  l2_lambda: 0.011018624740987784
  att_lambda: 1.0709908482857294e-05
  neg_sample_ratio: 0.5

GAT-Cora-EV2: &GAT-Cora-EV2  # 0.8369
  <<: *GAT-Cora-E
  attention_type: "dot_product"
  edge_sampling_ratio: 0.9489034517571067
  l2_lambda: 0.03524805465253446
  att_lambda: 0.0004901211756478777
  neg_sample_ratio: 0.6

GAT-Cora-EV2-nsr04: &GAT-Cora-EV2-nsr04  # 0.8372
  <<: *GAT-Cora-E
  attention_type: "dot_product"
  edge_sampling_ratio: 0.7193715100618308
  l2_lambda: 0.037567403739544133
  att_lambda: 0.011882874502325868
  neg_sample_ratio: 0.4

GAT-Cora-EV2O8: &GAT-Cora-EV2O8  # 0.8372
  <<: *GAT-Cora-EV2
  out_heads: 8
  edge_sampling_ratio: 0.7559580909152313
  l2_lambda: 0.017851237250470973
  att_lambda: 10.074546446345932
  neg_sample_ratio: 0.1

GAT-Cora-EV1-Link:
  <<: *GAT-Cora-EV1
  att_lambda: 5.449370600039373
  task_type: Link_Prediction

GAT-Cora-EV2-Link:
  <<: *GAT-Cora-EV2
  att_lambda: 5.449370600039373
  task_type: Link_Prediction

GAT-Cora-EV9: &GAT-Cora-EV9
  <<: *GAT-Cora-E
  attention_type: "prob_mask"
  total_pretraining_epoch: 1
  use_pretraining: True

GAT-Cora-EV9O8:
  <<: *GAT-Cora-EV9
  out_heads: 8
  edge_sampling_ratio: 0.9415869989676415
  l2_lambda: 0.010220007108586993
  att_lambda: 3.996741075453459
  total_pretraining_epoch: 74

GAT-Cora-EV9NSO8: &GAT-Cora-EV9NSO8  # 0.8499
  <<: *GAT-Cora-EV9
  out_heads: 8
  edge_sampling_ratio: 0.9468046761936069
  l2_lambda: 0.01208249146717384
  att_lambda: 4.290561542173698
  total_pretraining_epoch: 58
  neg_sample_ratio: 0.2

GAT-Cora-EV9NSO8-nsr03:  # 0.8502
  <<: *GAT-Cora-EV9
  out_heads: 8
  edge_sampling_ratio: 0.9288475885737304
  l2_lambda: 0.007953633092122336
  att_lambda: 3.249437442948412
  total_pretraining_epoch: 49
  neg_sample_ratio: 0.3

GAT-Cora-EV9NSPNO8:
  <<: *GAT-Cora-EV9
  out_heads: 8
  edge_sampling_ratio: 0.9468046761936069
  l2_lambda: 0.01208249146717384
  att_lambda: 4.290561542173698
  total_pretraining_epoch: 58
  neg_sample_ratio: 0.1
  pretraining_noise_ratio: 0.1

GAT-Cora-EV9O8MO:
  <<: *GAT-Cora-EV9
  out_heads: 8
  edge_sampling_ratio: 0.9415869989676415
  l2_lambda: 0.010220007108586993
  att_lambda: 3.996741075453459
  attention_type: "prob_mask_only"
  total_pretraining_epoch: 74
  neg_sample_ratio: 0.4

GAT-Cora-EV9O1:
  <<: *GAT-Cora-EV9
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.0001
  attention_type: "prob_mask"
  total_pretraining_epoch: 30

GAT-Cora-EV12: &GAT-Cora-EV12
  <<: *GAT-Cora-E
  attention_type: "prob_mask"

GAT-Cora-EV12O8:  # No pretraining
  <<: *GAT-Cora-EV12
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 3.3387640167333097

GAT-Cora-EV12NSO8: &GAT-Cora-EV12NSO8 # 0.8492
  <<: *GAT-Cora-EV12
  out_heads: 8
  edge_sampling_ratio: 0.5448325408142086
  l2_lambda: 0.009966526178313471
  att_lambda: 3.5536667418164765
  neg_sample_ratio: 0.7

GAT-Cora-EV12NSO8-nsr05: &GAT-Cora-EV12NSO8-nsr05 # *0.8492
  <<: *GAT-Cora-EV12
  out_heads: 8
  edge_sampling_ratio: 0.7737062345533201
  l2_lambda: 0.00936213531676361
  att_lambda: 3.045489874559996
  neg_sample_ratio: 0.5

GAT-Cora-EV12O8MO:  # No pretraining
  <<: *GAT-Cora-EV12
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 3.3387640167333097
  attention_type: "prob_mask_only"
  neg_sample_ratio: 0.4

GAT-Cora-NEV12O8:  # No pretraining
  <<: *GAT-Cora-EV12
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 0  # NEV

GAT-Cora-EV12O1:  # No pretraining
  <<: *GAT-Cora-EV12
  edge_sampling_ratio: 0.5001065133395246
  l2_lambda: 0.009822681226235598
  att_lambda: 1.8490524030529658

GAT-Cora-NEO8-ES-ATT:
  <<: *GAT-Cora-NEO8-ES
  task_type: Attention_Dist

GAT-Cora-NEDPO8-ES-ATT:
  <<: *GAT-Cora-NEDPO8-ES
  task_type: Attention_Dist


GAT-CiteSeer: &GAT-CiteSeer
  <<: *GAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-CiteSeer-NE: &GAT-CiteSeer-NE  # 0.7291
  <<: *GAT-CiteSeer
  epochs: 400
  l2_lambda: 0.0945514018495583
  is_super_gat: False

GAT-CiteSeer-NEO8: &GAT-CiteSeer-NEO8  # 0.7323
  <<: *GAT-CiteSeer-NE
  out_heads: 8
  l2_lambda: 0.04086304658243455

GAT-CiteSeer-NEDP:  # 0.7261
  <<: *GAT-CiteSeer-NE
  l2_lambda: 0.11448743924229177
  attention_type: "dot_product"

GAT-CiteSeer-NEDPO8: &GAT-CiteSeer-NEDPO8  # 0.7334
  <<: *GAT-CiteSeer-NE
  out_heads: 8
  l2_lambda: 0.048631720493287324
  attention_type: "dot_product"

GAT-CiteSeer-NEO8-ES: &GAT-CiteSeer-NEO8-ES
  <<: *GAT-CiteSeer-NEO8
  use_early_stop: True
  early_stop_patience: 215
  early_stop_queue_length: 326
  early_stop_threshold_loss: 0.00010558490126864286
  early_stop_threshold_perf: 7.261076847269871e-05
  epochs: 383

GAT-CiteSeer-NEDPO8-ES: &GAT-CiteSeer-NEDPO8-ES
  <<: *GAT-CiteSeer-NEDPO8
  use_early_stop: True
  early_stop_patience: 18
  early_stop_queue_length: 261
  early_stop_threshold_loss: 1.1710542353146263e-05
  early_stop_threshold_perf: 0.0002930891211324758
  epochs: 263

GAT-CiteSeer-EVL9O8:
  <<: *GAT-CiteSeer-NE
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  use_pretraining: True
  total_pretraining_epoch: 1
  edge_sampling_ratio: 0.65491644887445
  l2_lambda: 0.011374239383259618
  link_lambda: 0.1
  neg_sample_ratio: 0.7

GAT-CiteSeer-EVL12O8:  # 0.7356
  <<: *GAT-CiteSeer-NE
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  edge_sampling_ratio: 0.6642674136844611
  l2_lambda: 0.03974226235077282
  link_lambda: 0.47625745551384296
  neg_sample_ratio: 0.5

GAT-CiteSeer-EVL12O8-nsr03:  # 0.7365
  <<: *GAT-CiteSeer-NE
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  edge_sampling_ratio: 0.722253772705469
  l2_lambda: 0.04221775384501611
  link_lambda: 0.7808663904807999
  neg_sample_ratio: 0.3

GAT-CiteSeer-E: &GAT-CiteSeer-E
  <<: *GAT-CiteSeer
  epochs: 400
  is_super_gat: True

GAT-CiteSeer-EV1: &GAT-CiteSeer-EV1
  <<: *GAT-CiteSeer-E
  attention_type: "gat_originated"
  edge_sampling_ratio: 0.7078667583542126
  l2_lambda: 0.03794579277540424
  att_lambda: 0.045071824873627146

GAT-CiteSeer-EV1O8:  # 0.7336
  <<: *GAT-CiteSeer-EV1
  out_heads: 8
  edge_sampling_ratio: 0.570813536606956
  l2_lambda: 0.038447660492698044
  att_lambda: 0.0003951978268596114
  neg_sample_ratio: 0.3

GAT-CiteSeer-EV2: &GAT-CiteSeer-EV2
  <<: *GAT-CiteSeer-E
  attention_type: "dot_product"
  edge_sampling_ratio: 0.5039404411045578
  l2_lambda: 0.04777495641265913
  att_lambda: 0.6183687430239637

GAT-CiteSeer-EV2O8:  # 0.7339
  <<: *GAT-CiteSeer-EV2
  out_heads: 8
  edge_sampling_ratio: 0.9499077941001473
  l2_lambda: 0.04922437531304383
  att_lambda: 0.00656621522138879
  neg_sample_ratio: 0.5

GAT-CiteSeer-EV2O8-nsr01:  # 0.7339
  <<: *GAT-CiteSeer-EV2
  out_heads: 8
  edge_sampling_ratio: 0.9484953787205146
  l2_lambda: 0.04917687091495481
  att_lambda: 0.003379453260583774
  neg_sample_ratio: 0.1

GAT-CiteSeer-EV9: &GAT-CiteSeer-EV9
  <<: *GAT-CiteSeer-E
  attention_type: "prob_mask"
  total_pretraining_epoch: 1
  use_pretraining: True

GAT-CiteSeer-EV9O8:
  <<: *GAT-CiteSeer-EV9
  out_heads: 8
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  total_pretraining_epoch: 41

GAT-CiteSeer-EV9NSO8:
  <<: *GAT-CiteSeer-EV9
  out_heads: 8
  edge_sampling_ratio: 0.5007751734094837
  l2_lambda: 0.042423217328523846
  att_lambda: 0.00017009300368113955
  total_pretraining_epoch: 79
  neg_sample_ratio: 0.4

GAT-CiteSeer-EV9NSPNO8:
  <<: *GAT-CiteSeer-EV9
  out_heads: 8
  edge_sampling_ratio: 0.5007751734094837
  l2_lambda: 0.042423217328523846
  att_lambda: 0.00017009300368113955
  total_pretraining_epoch: 79
  neg_sample_ratio: 0.4
  pretraining_noise_ratio: 0.1

GAT-CiteSeer-EV9O8MO:
  <<: *GAT-CiteSeer-EV9
  out_heads: 8
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  attention_type: "prob_mask_only"
  total_pretraining_epoch: 41

GAT-CiteSeer-EV9O1:
  <<: *GAT-CiteSeer-EV9
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.0001
  attention_type: "prob_mask"
  total_pretraining_epoch: 30

GAT-CiteSeer-EV12: &GAT-CiteSeer-EV12  # No pretraining
  <<: *GAT-CiteSeer-E
  attention_type: "prob_mask"

GAT-CiteSeer-EV12O8:  # No pretraining  0.7374
  <<: *GAT-CiteSeer-EV12
  out_heads: 8
  edge_sampling_ratio: 0.9012908091978697
  l2_lambda: 0.041174833026475226
  att_lambda: 0.1964994137261087

GAT-CiteSeer-EV12NSO8:  # No pretraining
  <<: *GAT-CiteSeer-EV12
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  neg_sample_ratio: 0.4

GAT-CiteSeer-EV12O8MO:  # No pretraining
  <<: *GAT-CiteSeer-EV12
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask_only"

GAT-CiteSeer-NEV12O8:  # No pretraining
  <<: *GAT-CiteSeer-EV12
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0  # NEV

GAT-CiteSeer-EV12O1:  # No pretraining
  <<: *GAT-CiteSeer-EV12
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.1

GAT-CiteSeer-NEO8-ES-ATT:
  <<: *GAT-CiteSeer-NEO8-ES
  task_type: Attention_Dist

GAT-CiteSeer-NEDPO8-ES-ATT:
  <<: *GAT-CiteSeer-NEDPO8-ES
  task_type: Attention_Dist


GAT-PubMed: &GAT-PubMed
  <<: *GAT
  lr: 0.01
  out_heads: 8
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-PubMed-NE: &GAT-PubMed-NE
  <<: *GAT-PubMed
  epochs: 300
  l2_lambda: 0.0006334814661840428
  is_super_gat: False

GAT-PubMed-NE-500: &GAT-PubMed-NE-500  # 0.7911
  <<: *GAT-PubMed-NE
  epochs: 500
  l2_lambda: 0.0009634368245244388

GAT-PubMed-NEO1-500:  # 0.7873
  <<: *GAT-PubMed-NE
  out_heads: 1
  epochs: 500
  l2_lambda: 0.005149321249674828

GAT-PubMed-NEDP-500: &GAT-PubMed-NEDP-500  # 0.7954
  <<: *GAT-PubMed-NE
  epochs: 500
  l2_lambda: 0.0009233229073574351
  attention_type: "dot_product"

GAT-PubMed-NEDPO1-500:  # 0.7975
  <<: *GAT-PubMed-NE
  out_heads: 1
  epochs: 500
  l2_lambda: 0.0015809294634156696
  attention_type: "dot_product"

GAT-PubMed-NE-500-ES: &GAT-PubMed-NE-500-ES
  <<: *GAT-PubMed-NE-500
  use_early_stop: True
  early_stop_patience: 63
  early_stop_queue_length: 280
  early_stop_threshold_loss: 6.721676837434257e-05
  early_stop_threshold_perf: 0.04862386702167719
  epochs: 393

GAT-PubMed-NEDP-500-ES: &GAT-PubMed-NEDP-500-ES
  <<: *GAT-PubMed-NEDP-500
  use_early_stop: True
  early_stop_patience: 85
  early_stop_queue_length: 444
  early_stop_threshold_loss: 0.00013691430268719573
  early_stop_threshold_perf: 1.4531591237744876e-05
  epochs: 499

GAT-PubMed-EVL9O8-500:
  <<: *GAT-PubMed-NE
  epochs: 500
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  use_pretraining: True
  total_pretraining_epoch: 1
  edge_sampling_ratio: 0.5002892670247774
  l2_lambda: 0.0004808784359388049
  link_lambda: 0.590042928034016
  neg_sample_ratio: 0.7

GAT-PubMed-EVL12O8-500:  # 0.796
  <<: *GAT-PubMed-NE
  epochs: 500
  model_name: LinkGAT
  is_link_gnn: True
  out_heads: 8
  edge_sampling_ratio: 0.5002892670247774
  l2_lambda: 0.0004808784359388049
  link_lambda: 0.590042928034016
  neg_sample_ratio: 0.4

GAT-PubMed-E: &GAT-PubMed-E
  <<: *GAT-PubMed
  epochs: 300
  is_super_gat: True

GAT-PubMed-EV1-500:  # 0.7945
  <<: *GAT-PubMed-E
  epochs: 500
  edge_sampling_ratio: 0.784384051946587
  l2_lambda: 0.0008389396177399793
  att_lambda: 9.99770258575211
  attention_type: "gat_originated"
  neg_sample_ratio: 0.5

GAT-PubMed-EV2-500:  # 0.8234
  <<: *GAT-PubMed-E
  epochs: 500
  edge_sampling_ratio: 0.7974461865152842
  l2_lambda: 0.0001869403836078624
  att_lambda: 14.961085652013855
  attention_type: "dot_product"
  neg_sample_ratio: 0.3

GAT-PubMed-EV9O8: &GAT-PubMed-EV9O8
  <<: *GAT-PubMed-E
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  attention_type: "prob_mask"
  total_pretraining_epoch: 41
  use_pretraining: True

GAT-PubMed-EV9O8-500:
  <<: *GAT-PubMed-EV9O8
  epochs: 500
  edge_sampling_ratio: 0.5
  l2_lambda: 8.608275211233963e-05
  att_lambda: 31.622776601683793
  total_pretraining_epoch: 41

GAT-PubMed-EV9O8MO-500:
  <<: *GAT-PubMed-EV9O8
  epochs: 500
  edge_sampling_ratio: 0.5
  l2_lambda: 8.608275211233963e-05
  att_lambda: 31.622776601683793
  attention_type: "prob_mask_only"
  total_pretraining_epoch: 41

GAT-PubMed-EV9NSO8-500:  # 0.8261
  <<: *GAT-PubMed-EV9O8
  epochs: 500
  edge_sampling_ratio: 0.936623819585547
  l2_lambda: 1.0101541277934328e-05
  att_lambda: 30.691650700969998
  total_pretraining_epoch: 94
  neg_sample_ratio: 0.1

GAT-PubMed-EV9NSO8-500-nsr03:  # *0.8244
  <<: *GAT-PubMed-EV9O8
  epochs: 500
  edge_sampling_ratio: 0.9314710555750157
  l2_lambda: 0.00022586897944773404
  att_lambda: 24.00511704820566
  total_pretraining_epoch: 95
  neg_sample_ratio: 0.3

GAT-PubMed-EV9NSO8-500-nsr01:  # 0.8256
  <<: *GAT-PubMed-EV9O8
  epochs: 500
  edge_sampling_ratio: 0.9350997540901991
  l2_lambda: 1.4920597275804174e-05
  att_lambda: 31.095187100445685
  total_pretraining_epoch: 99
  neg_sample_ratio: 0.1

GAT-PubMed-EV9NSPNO8-500:
  <<: *GAT-PubMed-EV9O8
  epochs: 500
  edge_sampling_ratio: 0.936623819585547
  l2_lambda: 1.0101541277934328e-05
  att_lambda: 30.691650700969998
  total_pretraining_epoch: 94
  neg_sample_ratio: 0.1
  pretraining_noise_ratio: 0.1

GAT-PubMed-EV12O8: &GAT-PubMed-EV12O8  # No pretraining
  <<: *GAT-PubMed-E
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask"

GAT-PubMed-NEV12O8-500:  # No pretraining
  <<: *GAT-PubMed-EV12O8
  epochs: 500
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0  # NEV

GAT-PubMed-EV12O8-500:  # No pretraining
  <<: *GAT-PubMed-EV12O8
  epochs: 500
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324

GAT-PubMed-EV12O8MO-500:  # No pretraining
  <<: *GAT-PubMed-EV12O8
  epochs: 500
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask_only"

GAT-PubMed-EV12NSO8-500:  # No pretraining  # 0.8242
  <<: *GAT-PubMed-EV12O8
  epochs: 500
  edge_sampling_ratio: 0.7193106712559173
  l2_lambda: 0.0006251407173528253
  att_lambda: 10.798685163875442
  neg_sample_ratio: 0.5

GAT-PubMed-EV12NSO8-500-nsr05:  # No pretraining  # 0.8233
  <<: *GAT-PubMed-EV12O8
  epochs: 500
  edge_sampling_ratio: 0.79529612529846
  l2_lambda: 0.0006238195225073755
  att_lambda: 10.493501005383266
  neg_sample_ratio: 0.5

GAT-PubMed-NE-500-ES-ATT:
  <<: *GAT-PubMed-NE-500-ES
  task_type: Attention_Dist

GAT-PubMed-NEDP-500-ES-ATT:
  <<: *GAT-PubMed-NEDP-500-ES
  task_type: Attention_Dist


LargeGAT: &LargeGAT
  <<: *DEFAULT
  model_name: LargeGAT
  num_layers: 4

LargeGAT-Cora: &LargeGAT-Cora
  <<: *LargeGAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

LargeGAT-Cora-NEO8: &LargeGAT-Cora-NEO8
  <<: *LargeGAT-Cora
  epochs: 500
  out_heads: 8
  l2_lambda: 0.0
  is_super_gat: False

LargeGAT-Cora-NEDPO8: &LargeGAT-Cora-NEDPO8
  <<: *LargeGAT-Cora
  epochs: 500
  out_heads: 8
  l2_lambda: 0.03772977329580155
  is_super_gat: False
  attention_type: "dot_product"

LargeGAT-CiteSeer: &LargeGAT-CiteSeer
  <<: *LargeGAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

LargeGAT-CiteSeer-NEO8: &LargeGAT-CiteSeer-NEO8
  <<: *LargeGAT-CiteSeer
  epochs: 400
  is_super_gat: False
  out_heads: 8
  l2_lambda: 0.04086304658243455

LargeGAT-CiteSeer-NEDPO8: &LargeGAT-CiteSeer-NEDPO8
  <<: *LargeGAT-CiteSeer
  epochs: 400
  is_super_gat: False
  out_heads: 8
  l2_lambda: 0.048631720493287324
  attention_type: "dot_product"

LargeGAT-PubMed: &LargeGAT-PubMed
  <<: *LargeGAT
  lr: 0.01
  out_heads: 8
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

LargeGAT-PubMed-NE: &LargeGAT-PubMed-NE
  <<: *LargeGAT-PubMed
  epochs: 300
  l2_lambda: 0.0006334814661840428
  is_super_gat: False

LargeGAT-PubMed-NE-600: &LargeGAT-PubMed-NE-500
  <<: *LargeGAT-PubMed-NE
  epochs: 600
  l2_lambda: 0.0009634368245244388

LargeGAT-PubMed-NEDP-600: &LargeGAT-PubMed-NEDP-500
  <<: *LargeGAT-PubMed-NE
  epochs: 600
  l2_lambda: 0.0009233229073574351
  attention_type: "dot_product"
