DEFAULT: &DEFAULT
  black_list: [0, 2, 3]
  num_gpus_total: 4
  num_gpus_to_use: 1
  heads: 8
  dropout: 0.6
  edge_sampling_ratio: 0.9

  early_stop: True
  early_stop_threshold: -1
  seed: 42
  verbose: 2
  save_model: False
  save_plot: False


GAT: &GAT
  model_name: GAT
  <<: *DEFAULT

GAT-Cora: &GAT-Cora
  <<: *GAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-Cora-NE:  &GAT-Cora-NE
  <<: *GAT-Cora
  epochs: 500
  l2_lambda: 0.01174369781408157
  is_super_gat: False

GAT-Cora-NEO8:
  <<: *GAT-Cora-NE
  out_heads: 8
  l2_lambda: 0.01174369781408157

GAT-Cora-NEDP:
  <<: *GAT-Cora-NE
  l2_lambda: 0.01174369781408157
  attention_type: "dot_product"

GAT-Cora-NEDPO8:
  <<: *GAT-Cora-NE
  out_heads: 8
  l2_lambda: 0.01174369781408157
  attention_type: "dot_product"

GAT-Cora-E: &GAT-Cora-E
  <<: *GAT-Cora
  epochs: 500
  is_super_gat: True

GAT-Cora-EV1:
  <<: *GAT-Cora-E
  edge_sampling_ratio: 0.65491644887445
  l2_lambda: 0.011833069233159986
  att_lambda: 3.8805693322191623
  attention_type: "gat_originated"

GAT-Cora-EV2:
  <<: *GAT-Cora-E
  edge_sampling_ratio: 0.6057244078117906
  l2_lambda: 0.016754183821929596
  att_lambda: 5.449370600039373
  attention_type: "dot_product"

GAT-Cora-EV9:
  <<: *GAT-Cora-E
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.0001
  attention_type: "prob_mask"
  attention_pretraining_epoch: 30

GAT-Cora-EV9O8:  # 0.8507
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.9415869989676415
  l2_lambda: 0.010220007108586993
  att_lambda: 3.996741075453459
  attention_type: "prob_mask"
  attention_pretraining_epoch: 74

GAT-Cora-EV9NSO8:  # 0.8488
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.7909446129640284
  l2_lambda: 0.009518620121218525
  att_lambda: 5.023514220415577
  attention_type: "prob_mask"
  attention_pretraining_epoch: 55
  neg_sample_ratio: 0.4

GAT-Cora-EV9O8MO:
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.9415869989676415
  l2_lambda: 0.010220007108586993
  att_lambda: 3.996741075453459
  attention_type: "prob_mask_only"
  attention_pretraining_epoch: 74
  neg_sample_ratio: 0.4

GAT-Cora-EV9O1:
  <<: *GAT-Cora-E
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.0001
  attention_type: "prob_mask"
  attention_pretraining_epoch: 30

GAT-Cora-EV12:  # No pretraining
  <<: *GAT-Cora-E
  edge_sampling_ratio: 0.8337243750388602
  l2_lambda: 0.010303045568559648
  att_lambda: 3.6796767583404177
  attention_type: "prob_mask"

GAT-Cora-EV12O8:  # No pretraining  # 0.8493
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 3.3387640167333097
  attention_type: "prob_mask"

GAT-Cora-EV12NSO8:  # No pretraining
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 3.3387640167333097
  attention_type: "prob_mask"
  neg_sample_ratio: 0.4

GAT-Cora-EV12O8MO:  # No pretraining
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 3.3387640167333097
  attention_type: "prob_mask_only"
  neg_sample_ratio: 0.4

GAT-Cora-NEV12O8:  # No pretraining
  <<: *GAT-Cora-E
  out_heads: 8
  edge_sampling_ratio: 0.6977021924133151
  l2_lambda: 0.009591902680360786
  att_lambda: 0  # NEV
  attention_type: "prob_mask"

GAT-Cora-EV12O1:  # No pretraining
  <<: *GAT-Cora-E
  edge_sampling_ratio: 0.5001065133395246
  l2_lambda: 0.009822681226235598
  att_lambda: 1.8490524030529658
  attention_type: "prob_mask"


GAT-CiteSeer: &GAT-CiteSeer
  <<: *GAT
  lr: 0.005
  out_heads: 1
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-CiteSeer-NE: &GAT-CiteSeer-NE
  <<: *GAT-CiteSeer
  epochs: 400
  l2_lambda: 0.0388021344144113
  is_super_gat: False

GAT-CiteSeer-NEO8:
  <<: *GAT-CiteSeer-NE
  out_heads: 8
  l2_lambda: 0.03683992508624671

GAT-CiteSeer-NEDP:
  <<: *GAT-CiteSeer-NE
  l2_lambda: 0.0388021344144113
  attention_type: "dot_product"

GAT-CiteSeer-NEDPO8:
  <<: *GAT-CiteSeer-NE
  out_heads: 8
  l2_lambda: 0.0388021344144113
  attention_type: "dot_product"

GAT-CiteSeer-E: &GAT-CiteSeer-E
  <<: *GAT-CiteSeer
  epochs: 400
  is_super_gat: True

GAT-CiteSeer-EV1:
  <<: *GAT-CiteSeer-E
  edge_sampling_ratio: 0.7078667583542126
  l2_lambda: 0.03794579277540424
  att_lambda: 0.045071824873627146
  attention_type: "gat_originated"

GAT-CiteSeer-EV2:
  <<: *GAT-CiteSeer-E
  edge_sampling_ratio: 0.5039404411045578
  l2_lambda: 0.04777495641265913
  att_lambda: 0.6183687430239637
  attention_type: "dot_product"

GAT-CiteSeer-EV9:
  <<: *GAT-CiteSeer-E
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.0001
  attention_type: "prob_mask"
  attention_pretraining_epoch: 30

GAT-CiteSeer-EV9O8:  # 0.7436
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  attention_type: "prob_mask"
  attention_pretraining_epoch: 41

GAT-CiteSeer-EV9NSO8:
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  attention_type: "prob_mask"
  attention_pretraining_epoch: 41
  neg_sample_ratio: 0.4

GAT-CiteSeer-EV9O8MO:
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  attention_type: "prob_mask_only"
  attention_pretraining_epoch: 41

GAT-CiteSeer-EV9O1:
  <<: *GAT-CiteSeer-E
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.0001
  attention_type: "prob_mask"
  attention_pretraining_epoch: 30

GAT-CiteSeer-EV12:  # No pretraining
  <<: *GAT-CiteSeer-E
  edge_sampling_ratio: 0.5147794898949517
  l2_lambda: 0.03693839704585639
  att_lambda: 0.0022633421965065743
  attention_type: "prob_mask"

GAT-CiteSeer-EV12O8:  # No pretraining  0.7374
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.9012908091978697
  l2_lambda: 0.041174833026475226
  att_lambda: 0.1964994137261087
  attention_type: "prob_mask"

GAT-CiteSeer-EV12NSO8:  # No pretraining
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask"
  neg_sample_ratio: 0.4

GAT-CiteSeer-EV12O8MO:  # No pretraining
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask_only"

GAT-CiteSeer-NEV12O8:  # No pretraining
  <<: *GAT-CiteSeer-E
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0  # NEV
  attention_type: "prob_mask"

GAT-CiteSeer-EV12O1:  # No pretraining
  <<: *GAT-CiteSeer-E
  edge_sampling_ratio: 0.5
  l2_lambda: 0.0005
  att_lambda: 0.1
  attention_type: "prob_mask"


GAT-PubMed: &GAT-PubMed
  <<: *DEFAULT
  lr: 0.01
  out_heads: 8
  task_type: Node_Transductive
  val_interval: 1
  num_hidden_features: 8

GAT-PubMed-NE: &GAT-PubMed-NE
  <<: *GAT-PubMed
  epochs: 300
  l2_lambda: 0.0006334814661840428
  is_super_gat: False

GAT-PubMed-NE-500:
  <<: *GAT-PubMed-NE
  epochs: 500
  l2_lambda: 0.0006334814661840428

GAT-PubMed-NEDP:
  <<: *GAT-PubMed-NE
  l2_lambda: 0.0008387863766220923
  attention_type: "dot_product"

GAT-PubMed-E: &GAT-PubMed-E
  <<: *GAT-PubMed
  epochs: 300
  is_super_gat: True

GAT-PubMed-EV1:
  <<: *GAT-PubMed-E
  l2_lambda: 0.0006427648456884977
  att_lambda: 0.00033724064657300704
  attention_type: "gat_originated"

GAT-PubMed-EV2:
  <<: *GAT-PubMed-E
  edge_sampling_ratio: 0.6013315947726043
  l2_lambda: 0.0008249065014261066
  att_lambda: 0.36055516958817213
  attention_type: "dot_product"

GAT-PubMed-EV9O8:
  <<: *GAT-PubMed-E
  out_heads: 8
  edge_sampling_ratio: 0.5030357607832597
  l2_lambda: 0.0407014219526219
  att_lambda: 0.00016746130730858905
  attention_type: "prob_mask"
  attention_pretraining_epoch: 41

GAT-PubMed-EV9O8-500:
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.5
  l2_lambda: 8.608275211233963e-05
  att_lambda: 31.622776601683793
  attention_type: "prob_mask"
  attention_pretraining_epoch: 41

GAT-PubMed-EV9O8MO-500:
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.5
  l2_lambda: 8.608275211233963e-05
  att_lambda: 31.622776601683793
  attention_type: "prob_mask_only"
  attention_pretraining_epoch: 41

GAT-PubMed-EV9NSO8-500:
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.5
  l2_lambda: 8.608275211233963e-05
  att_lambda: 31.622776601683793
  attention_type: "prob_mask"
  attention_pretraining_epoch: 41
  neg_sample_ratio: 0.4

GAT-PubMed-EV9O8-600:
  <<: *GAT-PubMed-E
  epochs: 600
  out_heads: 8
  edge_sampling_ratio: 0.5703559155217857
  l2_lambda: 0.0006156780791779475
  att_lambda: 31.36031986441154
  attention_type: "prob_mask"
  attention_pretraining_epoch: 14

GAT-PubMed-EV12O8:  # No pretraining
  <<: *GAT-PubMed-E
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask"

GAT-PubMed-NEV12O8-500:  # No pretraining
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0  # NEV
  attention_type: "prob_mask"

GAT-PubMed-EV12O8-500:  # No pretraining
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask"

GAT-PubMed-EV12O8MO-500:  # No pretraining
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask_only"

GAT-PubMed-EV12NSO8-500:  # No pretraining
  <<: *GAT-PubMed-E
  epochs: 500
  out_heads: 8
  edge_sampling_ratio: 0.8626322691750812
  l2_lambda: 0.03866305390334028
  att_lambda: 0.01019006831591324
  attention_type: "prob_mask"
  neg_sample_ratio: 0.4

GAT-PubMed-EV12O8-600:  # No pretraining
  <<: *GAT-PubMed-E
  epochs: 600
  out_heads: 8
  edge_sampling_ratio: 0.94983674433696
  l2_lambda: 0.0002699072458331824
  att_lambda: 18.730971114251847
  attention_type: "prob_mask"


GAT-PPI: &GAT-PPI
  <<: *DEFAULT
  model_name: GATPPI
  dropout: 0.
  loss: nn.BCEWithLogitsLoss()
  lr: 0.005
  task_type: Node_Inductive
  val_interval: 1
  num_hidden_features: 128
  heads: 4
  out_heads: 6
  use_skip_connect_for_2: True

GAT-PPI-NE:
  <<: *GAT-PPI
  epochs: 130
  l2_lambda: 0.0
  is_super_gat: False

GAT-PPI-NE2:
  <<: *GAT-PPI
  epochs: 130
  l2_lambda: 0.0
  is_super_gat: False
  use_skip_connect_for_2: False

GAT-PPI-E: &GAT-PPI-E
  <<: *GAT-PPI
  epochs: 130
  is_super_gat: True

GAT-PPI-EV3:
  <<: *GAT-PPI-E
  edge_sampling_ratio: 0.65491644887445
  att_lambda: 0
  attention_type: "gat_originated"
  use_skip_connect_for_2: False

GAT-PPI-EV4:
  <<: *GAT-PPI-E
  edge_sampling_ratio: 0.65491644887445
  att_lambda: 0
  attention_type: "gat_originated"
  use_skip_connect_for_2: False
  super_gat_criterion: nn.L1Loss()