GATNet-DD-NE:
  model_name: GATNet
  task_type: Graph
  epochs: 100
  batch_size: 1
  l1_lambda: 1.5e-09
  l2_lambda: 4.1e-05

  save_model: False
  val_interval: 2

  head: 8
  dropout: 0.38
  num_hidden_features: 128
  pool_name: global_mean_pool  # None, global_mean_pool
  is_explicit: False

GATNet-Cora-NE:
  model_name: GATNet
  task_type: Node
  epochs: 500
  batch_size: 64
  l1_lambda: 7.4e-05
  l2_lambda: 7.2e-05

  save_model: False
  val_interval: 4

  head: 8
  dropout: 0.35
  num_hidden_features: 128
  is_explicit: False


GATNet-DD-E:
  model_name: GATNet
  task_type: Graph
  epochs: 100
  batch_size: 1
  l1_lambda: 1.5e-09
  l2_lambda: 4.1e-05

  save_model: False
  val_interval: 2

  head: 8
  dropout: 0.38
  num_hidden_features: 128
  pool_name: global_mean_pool  # None, global_mean_pool

  is_explicit: True
  possible_edges_factor: 10


GATNet-Cora-E:
  model_name: GATNet
  task_type: Node
  epochs: 500
  batch_size: 64
  l1_lambda: 7.4e-05
  l2_lambda: 7.2e-05

  save_model: False
  val_interval: 4

  head: 8
  dropout: 0.35
  num_hidden_features: 128

  is_explicit: True
  possible_edges_factor: 50
