DEFAULT: &DEFAULT
  model_name: GAT
  head: 8
  save_model: False

GAT-Cora: &GAT-Cora
  <<: *DEFAULT
  task_type: Node
  val_interval: 2
  num_hidden_features: 32

GAT-Cora-NE:
  <<: *GAT-Cora
  epochs: 500
  l2_lambda: 7.2e-05
  dropout: 0.6
  is_explicit: False

GAT-Cora-E: &GAT-Cora-E
  <<: *GAT-Cora
  epochs: 500
  is_explicit: True
  att_hidden_features: 2

GAT-Cora-EV1:
  <<: *GAT-Cora-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: multi

GAT-Cora-EV2:
  <<: *GAT-Cora-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: uni


GAT-CiteSeer: &GAT-CiteSeer
  <<: *DEFAULT
  task_type: Node
  val_interval: 2
  num_hidden_features: 32

GAT-CiteSeer-NE:
  <<: *GAT-CiteSeer
  epochs: 500
  l2_lambda: 7.2e-05
  dropout: 0.6
  is_explicit: False

GAT-CiteSeer-E: &GAT-CiteSeer-E
  <<: *GAT-CiteSeer
  epochs: 500
  is_explicit: True
  att_hidden_features: 2

GAT-CiteSeer-EV1:
  <<: *GAT-CiteSeer-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: multi

GAT-CiteSeer-EV2:
  <<: *GAT-CiteSeer-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: uni


GAT-PubMed: &GAT-PubMed
  <<: *DEFAULT
  task_type: Node
  val_interval: 2
  num_hidden_features: 32

GAT-PubMed-NE:
  <<: *GAT-PubMed
  epochs: 500
  l2_lambda: 7.2e-05
  dropout: 0.6
  is_explicit: False

GAT-PubMed-E: &GAT-PubMed-E
  <<: *GAT-PubMed
  epochs: 500
  is_explicit: True
  att_hidden_features: 2

GAT-PubMed-EV1:
  <<: *GAT-PubMed-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: multi

GAT-PubMed-EV2:
  <<: *GAT-PubMed-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: uni


GAT-NCI1: &GAT-NCI1
  <<: *DEFAULT
  task_type: Graph
  val_interval: 2
  num_hidden_features: 32
  batch_size: 128
  pool_name: global_mean_pool

GAT-NCI1-NE:
  <<: *GAT-NCI1
  epochs: 500
  l2_lambda: 7.2e-05
  dropout: 0.6
  is_explicit: False

GAT-NCI1-E: &GAT-NCI1-E
  <<: *GAT-NCI1
  epochs: 500
  is_explicit: True
  att_hidden_features: 2

GAT-NCI1-EV1:
  <<: *GAT-NCI1-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: multi

GAT-NCI1-EV2:
  <<: *GAT-NCI1-E
  l2_lambda: 7.2e-05
  dropout: 0.6
  att_lambda: 0.0467
  att_criterion: nn.NLLLoss()
  att_head_type: uni